### ISSUE TITLE
Заменить ImageMagick на gd

### ISSUE THREAD

**Issue by powder96** [feedbee/habrometr#10]
Предлагаю заменить ImageMagick на более популярный gd. Можно использовать pChart 2.1.3 (GPL), чтобы получить сглаженные линии и готовые алгоритмы рендеринга графиков.

Пользы никакой, кроме того, что хаброметр будет работать на большем числе хостов.

**Comment by feedbee** [comment]
Просто так менять IM на GD смысла нет. От сглаженных кривых я отказался в пользу ломанных в самом начале, т.к. они плохо передают точность. Не спорю, что над эстетикой графиков еще можно поработать, но от себя я уже выжал все, что мог. Так что теперь могу предложить подключиться к разработке и слать патчи. Если у вас реально получится лучше, чем есть сейчас, код обязательно попадет в master и на habrometr.ru.

**Comment by powder96** [comment]
Под сглаженными линиями я подразумевал антиалиасинг.

Если удастся побороть лень, то сделаю патч :)
